### PR TITLE
V3 android cmake support Lua & JS

### PR DESCRIPTION
**Pull request by drelaptop**
some fix about other test-projects cmake build on android

`lua-empty-test`, cmake compile success, but run failed, need check

we can do it together, to make `cmake support Android` be finished earlier.

### CODE REVIEW

**Comment by drelaptop** [comment]
Now, `lua_empty_test` `lua-tests` project support CMake build on android , `lua-template` not yet

**Comment by drelaptop** [comment]
@newnon would you like do a review for this PR?

This PR let CMake support Lua & JS project on Android platform.

**Comment by newnon** [comment]
ok i'll review in in thew hours

**Comment by newnon** [comment]
@drelaptop did you decide to make cmake default build system?
PROP_NDK_MODE=cmake ?

**Comment by drelaptop** [comment]
yep, I want to do that. make cmake as default build system. it will have a benefit to spread the way of cmake build among developers. 

our final goal is making cmake support all platforms.

**Pull request merged**
